### ISSUE TITLE
Bot is offline

### ISSUE THREAD

**Issue by feralheart** [JABirchall/botman-driver-discord#4]
I used this package with Botman Studio, and after the oAuth connection it connects to the server, but remains offline. Why?

**Comment by JABirchall** [comment]
Botman studio is designed to create chatbot for websites or perform actions on requests. It is recommended to run discord over CLI for continuous connection.

**Comment by feralheart** [comment]
Than Botman and Discord would never work together?

**Comment by JABirchall** [comment]
They do, but not botman studio. You to use the base botman library.

[Botman/Botman](https://github.com/botman/botman/)

**Comment by feralheart** [comment]
And if I implement Botman under Laravel but without Botman Studio, will it work?

**Comment by JABirchall** [comment]
No. If you are wanting to create a bot for discord it will not work with any **web** framework.
The discord driver is designed for **CLI** use.

Unless you are creating a bot to delegate customer engagment on a business website, you dont need botman studio.
Discord requires a continous connection, running over a web framework wont support that.

**Comment by feralheart** [comment]
And what's the difference between Botman Studio and Laravel under Botman?
Which part disallows using Botman Studio and Discord together?

Jake Birchall <notifications@github.com> ezt írta (időpont: 2019. ápr. 6.,
Szo 16:33):

**Comment by JABirchall** [comment]
I had editted my comment, but it looks like you are repling via email so you will not see the edit, So here is what I edited my comment too.

> If you are wanting to create a bot for discord it will not work with any web framework.
> The discord driver is designed for CLI use only.
> 
> Unless you are creating a bot to delegate customer engagement on a business website, you don't need botman studio.
> Discord requires a continous connection, running over a web framework wont support that.

As to what blocks it, ReactNative blocks it. Or the correct term, gets blocked by it. ReactNative is asynchronous, Laravel is not, very much not.

**Comment by feralheart** [comment]
Thank you, now I managed to work, I will make a pull request, soon :)
