### ISSUE TITLE
[BLOCKED] Botman react/socket outdated

### ISSUE THREAD

**Issue by JABirchall** [JABirchall/botman-driver-discord#6]
This issue is to mark that we are trying to upgrade the discord driver. However, the botman base requires react/socket ^0.4 while the latest version is  ^1.2 and multiple libraries we are using to upgrade the driver requires ^1.1. This is blocking us from releasing 1.1.0 of the driver

Ref: https://github.com/botman/botman/issues/1001#issue-432895716

**Comment by feralheart** [comment]
I managed to upgrade the react/socket to the latest version with requiring it in the composer.json.
I know it's not the best fix, but 'til Marcel releases the update it will be good enough :)
