### ISSUE TITLE
Using multiple sockets

### ISSUE THREAD

**Issue by feralheart** [JABirchall/botman-driver-discord#8]
I want to run more bots simultaneusly.
Can I configure the websocket url with a custom attribute?
For example:
bot1: `websocketUrl?bot=testBot`
bot2: `websocketUrl?bot=musicBot`

**Comment by JABirchall** [comment]
The discord drivers support multiple servers per bot this by default, simple invite the bot to different servers you want to use it on.
If you are wanting to use multiple users, I don't think botman can support this.

**Comment by JABirchall** [comment]
Actually, botman might support it. but you will need to build multiple botman clients.
```php
$config = [
    [
        'discord' =>[
        'token' => "your token",
        ],
    ],
    [
        'discord' =>[
            'token' => "your token",
        ],
    ]
];

DriverManager::loadDriver(\JABirchall\BotMan\Drivers\Discord\DiscordDriver::class);
$loop = Factory::create();
$botman1 = BotManFactory::createForDiscord($config[0], $loop);
$botman2 = BotManFactory::createForDiscord($config[1], $loop);

// Give the bot something to listen for.
$botman1->hears('hello', function (BotMan $bot) {
    $bot->reply('Hello yourself.');
});
$botman2->hears('bye', function (BotMan $bot) {
    $bot->reply('bye');
});
// Start listening
$botman1->listen();
$botman2->listen();
$loop->run();
```

Might work.
